import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/custom/Header";
import { ClerkProvider, } from '@clerk/nextjs'
import QueryClientProviderComp from "@/components/custom/QueryClientProvider";
import { ReactQueryDevtools } from '@tanstack/react-query-devtools'
import { Toaster } from "@/components/ui/toaster"



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Online Streaming App",
  description: "Generated by zain",
};

export default function RootLayout({
  children,


}: Readonly<{
  children: React.ReactNode;

}>) {


  return (
    <ClerkProvider>
      <html lang="en">
        <>

          <body className={inter.className}>
            <QueryClientProviderComp>
              <Header></Header>
              <main className="relative z-10">
                {children}

              </main>
              <Toaster />
              <ReactQueryDevtools></ReactQueryDevtools>
            </QueryClientProviderComp>
          </body>

        </>
      </html>
    </ClerkProvider>

  );
}
